apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-deployment
  labels:
    app: api-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-test
  template:
    metadata:
      labels:
        app: api-test
    spec:
      containers:
      - name: api-test-container
        image: lastknight01/gitops-demo:v2.1
        ports:
        - containerPort: 8080
